package database

import "database/sql"

var cwViews = []ColumnViews{
	{
		name: "v_cw_stmt_core",
		from: "raw_caiwu",
		desc: "1. 三大报表原始+单季核心",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f0", alias: "eps_basic", desc: "基本每股收益"},
			{name: "f1", alias: "eps_basic_excl_extra", desc: "扣除非经常性损益每股收益"},
			{name: "f2", alias: "retained_earnings_ps", desc: "每股未分配利润"},
			{name: "f3", alias: "net_assets_ps", desc: "每股净资产"},
			{name: "f4", alias: "capital_reserve_ps", desc: "每股资本公积金"},
			{name: "f5", alias: "roe", desc: "净资产收益率"},
			{name: "f6", alias: "operating_cf_ps", desc: "每股经营现金流量"},
			{name: "f7", alias: "monetary_funds", desc: "货币资金"},
			{name: "f8", alias: "trading_financial_assets", desc: "交易性金融资产"},
			{name: "f9", alias: "notes_receivable", desc: "应收票据"},
			{name: "f10", alias: "accounts_receivable", desc: "应收账款"},
			{name: "f11", alias: "prepayments", desc: "预付款项"},
			{name: "f12", alias: "other_receivables", desc: "其他应收款"},
			{name: "f13", alias: "receivables_from_related_parties", desc: "应收关联公司款"},
			{name: "f14", alias: "interest_receivable", desc: "应收利息"},
			{name: "f15", alias: "dividends_receivable", desc: "应收股利"},
			{name: "f16", alias: "inventories", desc: "存货"},
			{name: "f17", alias: "consumptive_bio_assets", desc: "其中：消耗性生物资产"},
			{name: "f18", alias: "noncurrent_assets_due_within_1y", desc: "一年内到期的非流动资产"},
			{name: "f19", alias: "other_current_assets", desc: "其他流动资产"},
			{name: "f20", alias: "total_current_assets", desc: "流动资产合计"},
			{name: "f21", alias: "afs_financial_assets", desc: "可供出售金融资产"},
			{name: "f22", alias: "held_to_maturity_investments", desc: "持有至到期投资"},
			{name: "f23", alias: "long_term_receivables", desc: "长期应收款"},
			{name: "f24", alias: "long_term_equity_investments", desc: "长期股权投资"},
			{name: "f25", alias: "investment_properties", desc: "投资性房地产"},
			{name: "f26", alias: "fixed_assets", desc: "固定资产"},
			{name: "f27", alias: "construction_in_progress", desc: "在建工程"},
			{name: "f28", alias: "construction_materials", desc: "工程物资"},
			{name: "f29", alias: "fixed_assets_disposal", desc: "固定资产清理"},
			{name: "f30", alias: "productive_bio_assets", desc: "生产性生物资产"},
			{name: "f31", alias: "oil_gas_assets", desc: "油气资产"},
			{name: "f32", alias: "intangible_assets", desc: "无形资产"},
			{name: "f33", alias: "development_expenditure", desc: "开发支出"},
			{name: "f34", alias: "goodwill", desc: "商誉"},
			{name: "f35", alias: "long_term_prepaid_expenses", desc: "长期待摊费用"},
			{name: "f36", alias: "deferred_tax_assets", desc: "递延所得税资产"},
			{name: "f37", alias: "other_noncurrent_assets", desc: "其他非流动资产"},
			{name: "f38", alias: "total_noncurrent_assets", desc: "非流动资产合计"},
			{name: "f39", alias: "total_assets", desc: "资产总计"},
			{name: "f40", alias: "short_term_borrowings", desc: "短期借款"},
			{name: "f41", alias: "trading_financial_liabilities", desc: "交易性金融负债"},
			{name: "f42", alias: "notes_payable", desc: "应付票据"},
			{name: "f43", alias: "accounts_payable", desc: "应付账款"},
			{name: "f44", alias: "advances_from_customers", desc: "预收款项"},
			{name: "f45", alias: "payroll_payable", desc: "应付职工薪酬"},
			{name: "f46", alias: "taxes_payable", desc: "应交税费"},
			{name: "f47", alias: "interest_payable", desc: "应付利息"},
			{name: "f48", alias: "dividends_payable", desc: "应付股利"},
			{name: "f49", alias: "other_payables", desc: "其他应付款"},
			{name: "f50", alias: "payables_to_related_parties", desc: "应付关联公司款"},
			{name: "f51", alias: "noncurrent_liabilities_due_within_1y", desc: "一年内到期的非流动负债"},
			{name: "f52", alias: "other_current_liabilities", desc: "其他流动负债"},
			{name: "f53", alias: "total_current_liabilities", desc: "流动负债合计"},
			{name: "f54", alias: "long_term_borrowings", desc: "长期借款"},
			{name: "f55", alias: "bonds_payable", desc: "应付债券"},
			{name: "f56", alias: "long_term_payables", desc: "长期应付款"},
			{name: "f57", alias: "specific_payables", desc: "专项应付款"},
			{name: "f58", alias: "provisions", desc: "预计负债"},
			{name: "f59", alias: "deferred_tax_liabilities", desc: "递延所得税负债"},
			{name: "f60", alias: "other_noncurrent_liabilities", desc: "其他非流动负债"},
			{name: "f61", alias: "total_noncurrent_liabilities", desc: "非流动负债合计"},
			{name: "f62", alias: "total_liabilities", desc: "负债合计"},
			{name: "f63", alias: "share_capital", desc: "实收资本（或股本）"},
			{name: "f64", alias: "capital_reserve", desc: "资本公积"},
			{name: "f65", alias: "surplus_reserve", desc: "盈余公积"},
			{name: "f66", alias: "treasury_shares", desc: "减：库存股"},
			{name: "f67", alias: "retained_earnings", desc: "未分配利润"},
			{name: "f68", alias: "minority_interests", desc: "少数股东权益"},
			{name: "f69", alias: "fx_translation_reserve", desc: "外币报表折算价差"},
			{name: "f70", alias: "abnormal_items_adjustment", desc: "非正常经营项目收益调整"},
			{name: "f71", alias: "total_equity", desc: "所有者权益（或股东权益）合计"},
			{name: "f72", alias: "total_liabilities_and_equity", desc: "负债和所有者（或股东权益）合计"},
			{name: "f270", alias: "equity_attributable_to_owners", desc: "归属于母公司股东权益"},
			{name: "f294", alias: "notes_and_accounts_payable", desc: "应付票据及应付账款"},
			{name: "f295", alias: "notes_and_accounts_receivable", desc: "应收票据及应收账款"},
			{name: "f296", alias: "deferred_income", desc: "递延收益"},
			{name: "f297", alias: "other_comprehensive_income", desc: "其他综合收益"},
			{name: "f298", alias: "other_equity_instruments", desc: "其他权益工具"},
			{name: "f73", alias: "operating_revenue", desc: "营业收入"},
			{name: "f74", alias: "operating_cost", desc: "营业成本"},
			{name: "f75", alias: "business_taxes_and_surcharges", desc: "营业税金及附加"},
			{name: "f76", alias: "selling_expenses", desc: "销售费用"},
			{name: "f77", alias: "administrative_expenses", desc: "管理费用"},
			{name: "f78", alias: "exploration_expenses", desc: "勘探费用"},
			{name: "f79", alias: "finance_expenses", desc: "财务费用"},
			{name: "f80", alias: "asset_impairment_losses", desc: "资产减值损失"},
			{name: "f81", alias: "fair_value_gain", desc: "公允价值变动净收益"},
			{name: "f82", alias: "investment_income", desc: "投资收益"},
			{name: "f83", alias: "income_from_associates_and_joint_ventures", desc: "对联营企业和合营企业的投资收益"},
			{name: "f84", alias: "other_items_affecting_operating_profit", desc: "影响营业利润的其他科目"},
			{name: "f85", alias: "operating_profit", desc: "营业利润"},
			{name: "f86", alias: "subsidy_income", desc: "补贴收入"},
			{name: "f87", alias: "non_operating_income", desc: "营业外收入"},
			{name: "f88", alias: "non_operating_expenses", desc: "营业外支出"},
			{name: "f89", alias: "loss_on_disposal_of_noncurrent_assets", desc: "非流动资产处置净损失"},
			{name: "f90", alias: "other_items_affecting_total_profit", desc: "影响利润总额的其他科目"},
			{name: "f91", alias: "total_profit", desc: "利润总额"},
			{name: "f92", alias: "income_tax_expense", desc: "所得税"},
			{name: "f93", alias: "other_items_affecting_net_profit", desc: "影响净利润的其他科目"},
			{name: "f94", alias: "net_profit", desc: "净利润"},
			{name: "f95", alias: "net_profit_attributable_to_owners", desc: "归属于母公司股东的净利润"},
			{name: "f96", alias: "profit_attributable_to_minority_interests", desc: "少数股东损益"},
			{name: "f300", alias: "gain_on_disposal_of_assets", desc: "资产处置收益"},
			{name: "f301", alias: "net_profit_from_continuing_operations", desc: "持续经营净利润"},
			{name: "f302", alias: "net_profit_from_discontinued_operations", desc: "终止经营净利润"},
			{name: "f303", alias: "r_and_d_expenses", desc: "研发费用"},
			{name: "f229", alias: "operating_revenue_q", desc: "营业收入（单季度）"},
			{name: "f230", alias: "operating_profit_q", desc: "营业利润（单季度）"},
			{name: "f231", alias: "net_profit_attributable_to_owners_q", desc: "归母净利润（单季度）"},
			{name: "f232", alias: "net_profit_excl_extra_q", desc: "扣非净利润（单季度）"},
			{name: "f233", alias: "net_cash_from_operating_activities_q", desc: "经营活动产生的现金流量净额（单季度）"},
			{name: "f234", alias: "net_cash_from_investing_activities_q", desc: "投资活动产生的现金流量净额（单季度）"},
			{name: "f235", alias: "net_cash_from_financing_activities_q", desc: "筹资活动产生的现金流量净额（单季度）"},
			{name: "f236", alias: "net_increase_in_cash_eq_q", desc: "现金及现金等价物净增加额（单季度）"},
			{name: "f310", alias: "eps_basic_q", desc: "基本每股收益（单季度）"},
			{name: "f97", alias: "cash_received_from_sales_and_services", desc: "销售商品、提供劳务收到的现金"},
			{name: "f98", alias: "tax_refunds_received", desc: "收到的税费返还"},
			{name: "f99", alias: "other_operating_cash_inflows", desc: "收到其他与经营活动有关的现金"},
			{name: "f100", alias: "total_operating_cash_inflows", desc: "经营活动现金流入小计"},
			{name: "f101", alias: "cash_paid_for_goods_and_services", desc: "购买商品、接受劳务支付的现金"},
			{name: "f102", alias: "cash_paid_to_and_on_behalf_of_employees", desc: "支付给职工以及为职工支付的现金"},
			{name: "f103", alias: "cash_paid_for_taxes", desc: "支付的各项税费"},
			{name: "f104", alias: "other_operating_cash_outflows", desc: "支付其他与经营活动有关的现金"},
			{name: "f105", alias: "total_operating_cash_outflows", desc: "经营活动现金流出小计"},
			{name: "f106", alias: "net_cash_from_operating_activities", desc: "经营活动产生的现金流量净额"},
			{name: "f107", alias: "cash_received_from_disposal_of_investments", desc: "收回投资收到的现金"},
			{name: "f108", alias: "cash_received_from_investment_income", desc: "取得投资收益收到的现金"},
			{name: "f109", alias: "cash_received_from_disposal_of_long_term_assets", desc: "处置固定资产、无形资产和其他长期资产收回的现金净额"},
			{name: "f110", alias: "net_cash_received_from_disposal_of_subsidiaries", desc: "处置子公司及其他营业单位收到的现金净额"},
			{name: "f111", alias: "other_investing_cash_inflows", desc: "收到其他与投资活动有关的现金"},
			{name: "f112", alias: "total_investing_cash_inflows", desc: "投资活动现金流入小计"},
			{name: "f113", alias: "cash_paid_for_acquisition_of_long_term_assets", desc: "购建固定资产、无形资产和其他长期资产支付的现金"},
			{name: "f114", alias: "cash_paid_for_investments", desc: "投资支付的现金"},
			{name: "f115", alias: "net_cash_paid_for_acquisition_of_subsidiaries", desc: "取得子公司及其他营业单位支付的现金净额"},
			{name: "f116", alias: "other_investing_cash_outflows", desc: "支付其他与投资活动有关的现金"},
			{name: "f117", alias: "total_investing_cash_outflows", desc: "投资活动现金流出小计"},
			{name: "f118", alias: "net_cash_from_investing_activities", desc: "投资活动产生的现金流量净额"},
			{name: "f119", alias: "cash_received_from_investors", desc: "吸收投资收到的现金"},
			{name: "f120", alias: "cash_received_from_borrowings", desc: "取得借款收到的现金"},
			{name: "f121", alias: "other_financing_cash_inflows", desc: "收到其他与筹资活动有关的现金"},
			{name: "f122", alias: "total_financing_cash_inflows", desc: "筹资活动现金流入小计"},
			{name: "f123", alias: "cash_repaid_for_debts", desc: "偿还债务支付的现金"},
			{name: "f124", alias: "cash_paid_for_dividends_and_interest", desc: "分配股利、利润或偿付利息支付的现金"},
			{name: "f125", alias: "other_financing_cash_outflows", desc: "支付其他与筹资活动有关的现金"},
			{name: "f126", alias: "total_financing_cash_outflows", desc: "筹资活动现金流出小计"},
			{name: "f127", alias: "net_cash_from_financing_activities", desc: "筹资活动产生的现金流量净额"},
			{name: "f128", alias: "effect_of_fx_changes_on_cash", desc: "汇率变动对现金的影响"},
			{name: "f129", alias: "effect_of_other_changes_on_cash", desc: "其他原因对现金的影响"},
			{name: "f130", alias: "net_increase_in_cash_eq", desc: "现金及现金等价物净增加额"},
			{name: "f131", alias: "cash_eq_at_beginning_of_period", desc: "期初现金及现金等价物余额"},
			{name: "f132", alias: "cash_eq_at_end_of_period", desc: "期末现金及现金等价物余额"},
			{name: "f133", alias: "net_profit_cf", desc: "净利润（现金流量表补充）"},
			{name: "f134", alias: "provision_for_asset_impairment", desc: "资产减值准备"},
			{name: "f135", alias: "depreciation_and_depletion", desc: "固定资产折旧、油气资产折耗、生产性生物资产折旧"},
			{name: "f136", alias: "amortisation_of_intangibles", desc: "无形资产摊销"},
			{name: "f137", alias: "amortisation_of_long_term_prepaid_expenses", desc: "长期待摊费用摊销"},
			{name: "f138", alias: "loss_on_disposal_of_long_term_assets", desc: "处置固定资产、无形资产和其他长期资产的损失"},
			{name: "f139", alias: "loss_on_retirement_of_fixed_assets", desc: "固定资产报废损失"},
			{name: "f140", alias: "loss_from_changes_in_fair_value", desc: "公允价值变动损失"},
			{name: "f141", alias: "finance_costs_cf", desc: "财务费用（补充资料）"},
			{name: "f142", alias: "investment_losses", desc: "投资损失"},
			{name: "f143", alias: "decrease_in_deferred_tax_assets", desc: "递延所得税资产减少"},
			{name: "f144", alias: "increase_in_deferred_tax_liabilities", desc: "递延所得税负债增加"},
			{name: "f145", alias: "decrease_in_inventories", desc: "存货的减少"},
			{name: "f146", alias: "decrease_in_operating_receivables", desc: "经营性应收项目的减少"},
			{name: "f147", alias: "increase_in_operating_payables", desc: "经营性应付项目的增加"},
			{name: "f148", alias: "other_cf_adjustments", desc: "其他（现金流量调整）"},
			{name: "f149", alias: "net_cash_from_operating_activities_alt", desc: "经营活动产生的现金流量净额2"},
			{name: "f150", alias: "debt_to_capital", desc: "债务转为资本"},
			{name: "f151", alias: "convertible_bonds_due_within_1y", desc: "一年内到期的可转换公司债券"},
			{name: "f152", alias: "finance_leased_fixed_assets", desc: "融资租入固定资产"},
			{name: "f153", alias: "cash_ending_balance", desc: "现金的期末余额"},
			{name: "f154", alias: "cash_beginning_balance", desc: "现金的期初余额"},
			{name: "f155", alias: "cash_equivalents_ending_balance", desc: "现金等价物的期末余额"},
			{name: "f156", alias: "cash_equivalents_beginning_balance", desc: "现金等价物的期初余额"},
			{name: "f157", alias: "net_increase_in_cash_and_equivalents", desc: "现金及现金等价物净增加额"},
			{name: "f306", alias: "ocf_last_12m", desc: "近一年经营活动现金流净额"},
			{name: "f307", alias: "net_profit_attributable_to_owners_last_12m", desc: "近一年归母净利润（万元）"},
			{name: "f308", alias: "net_profit_excl_extra_last_12m", desc: "近一年扣非净利润（万元）"},
			{name: "f309", alias: "net_cash_flow_last_12m", desc: "近一年现金净流量（万元）"},
			{name: "f315", alias: "icf_last_12m", desc: "近一年投资活动现金流净额(万元)"},
			{name: "f320", alias: "free_cf_to_firm_ps", desc: "每股企业自由现金流"},
			{name: "f321", alias: "free_cf_to_equity_ps", desc: "每股股东自由现金流"},
		},
	},
	{
		name: "v_cw_ratio_quality",
		from: "raw_caiwu",
		desc: "2. 现金流结构与质量 比率、盈利质量、成长性 因子",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f158", alias: "current_ratio", desc: "流动比率"},
			{name: "f159", alias: "quick_ratio", desc: "速动比率"},
			{name: "f160", alias: "cash_ratio", desc: "现金比率(%)"},
			{name: "f161", alias: "interest_coverage_ratio", desc: "利息保障倍数"},
			{name: "f162", alias: "noncurrent_liability_ratio", desc: "非流动负债比率(%)"},
			{name: "f163", alias: "current_liability_ratio", desc: "流动负债比率(%)"},
			{name: "f164", alias: "cash_to_maturing_debt_ratio", desc: "现金到期债务比率(%)"},
			{name: "f165", alias: "tangible_net_worth_to_debt_ratio", desc: "有形资产净值债务率(%)"},
			{name: "f166", alias: "equity_multiplier", desc: "权益乘数(%)"},
			{name: "f167", alias: "equity_to_total_liabilities_ratio", desc: "股东的权益/负债合计(%)"},
			{name: "f168", alias: "tangible_assets_to_total_liabilities_ratio", desc: "有形资产/负债合计(%)"},
			{name: "f169", alias: "ocf_to_total_liabilities_ratio", desc: "经营活动现金流净额/负债合计(%)"},
			{name: "f170", alias: "ebitda_to_total_liabilities_ratio", desc: "EBITDA/负债合计(%)"},
			{name: "f171", alias: "ar_turnover", desc: "应收账款周转率"},
			{name: "f172", alias: "inventory_turnover", desc: "存货周转率"},
			{name: "f173", alias: "working_capital_turnover", desc: "营运资金周转率"},
			{name: "f174", alias: "total_asset_turnover", desc: "总资产周转率"},
			{name: "f175", alias: "fixed_asset_turnover", desc: "固定资产周转率"},
			{name: "f176", alias: "ar_turnover_days", desc: "应收账款周转天数"},
			{name: "f177", alias: "inventory_turnover_days", desc: "存货周转天数"},
			{name: "f178", alias: "current_asset_turnover", desc: "流动资产周转率"},
			{name: "f179", alias: "current_asset_turnover_days", desc: "流动资产周转天数"},
			{name: "f180", alias: "total_asset_turnover_days", desc: "总资产周转天数"},
			{name: "f181", alias: "equity_turnover", desc: "股东权益周转率"},
			{name: "f182", alias: "revenue_growth_rate", desc: "营业收入增长率(%)"},
			{name: "f183", alias: "net_profit_growth_rate", desc: "净利润增长率(%)"},
			{name: "f184", alias: "net_assets_growth_rate", desc: "净资产增长率(%)"},
			{name: "f185", alias: "fixed_assets_growth_rate", desc: "固定资产增长率(%)"},
			{name: "f186", alias: "total_assets_growth_rate", desc: "总资产增长率(%)"},
			{name: "f187", alias: "investment_income_growth_rate", desc: "投资收益增长率(%)"},
			{name: "f188", alias: "operating_profit_growth_rate", desc: "营业利润增长率(%)"},
			{name: "f189", alias: "eps_excl_extra_yoy", desc: "扣非每股收益同比(%)"},
			{name: "f190", alias: "net_profit_excl_extra_yoy", desc: "扣非净利润同比(%)"},
			{name: "f192", alias: "cost_expense_profit_ratio", desc: "成本费用利润率(%)"},
			{name: "f193", alias: "operating_margin", desc: "营业利润率"},
			{name: "f194", alias: "business_taxes_rate", desc: "营业税金率"},
			{name: "f195", alias: "operating_cost_ratio", desc: "营业成本率"},
			{name: "f196", alias: "roe_alt", desc: "净资产收益率（另一口径）"},
			{name: "f197", alias: "investment_return_ratio", desc: "投资收益率"},
			{name: "f198", alias: "net_margin", desc: "销售净利率(%)"},
			{name: "f199", alias: "roa", desc: "总资产净利率(ROA)"},
			{name: "f200", alias: "net_profit_margin", desc: "净利润率"},
			{name: "f201", alias: "gross_margin", desc: "销售毛利率(%)"},
			{name: "f202", alias: "three_expenses_ratio", desc: "三费比重"},
			{name: "f203", alias: "admin_expense_ratio", desc: "管理费用率"},
			{name: "f204", alias: "finance_expense_ratio", desc: "财务费用率"},
			{name: "f205", alias: "net_profit_excl_extra", desc: "扣除非经常性损益后的净利润"},
			{name: "f206", alias: "ebit", desc: "息税前利润"},
			{name: "f207", alias: "ebitda", desc: "息税折旧摊销前利润"},
			{name: "f208", alias: "ebitda_margin", desc: "EBITDA/营业总收入(%)"},
			{name: "f209", alias: "debt_to_asset_ratio", desc: "资产负债率(%)"},
			{name: "f210", alias: "current_assets_ratio", desc: "流动资产比率"},
			{name: "f211", alias: "monetary_funds_ratio", desc: "货币资金比率"},
			{name: "f212", alias: "inventory_ratio", desc: "存货比率"},
			{name: "f213", alias: "fixed_assets_ratio", desc: "固定资产比率"},
			{name: "f214", alias: "liability_structure_ratio", desc: "负债结构比"},
			{name: "f215", alias: "equity_to_total_invested_capital_ratio", desc: "归母权益/全部投入资本(%)"},
			{name: "f216", alias: "equity_to_interest_bearing_debt_ratio", desc: "股东权益/带息债务(%)"},
			{name: "f217", alias: "tangible_assets_to_net_debt_ratio", desc: "有形资产/净债务(%)"},
			{name: "f280", alias: "roe_weighted", desc: "加权净资产收益率"},
			{name: "f318", alias: "revenue_ttm", desc: "营业总收入TTM(万元)"},
			{name: "f328", alias: "roic", desc: "投入资本回报率(ROIC)"},
			{name: "f336", alias: "dividend_payout_ratio", desc: "股利支付率(%)"},
		},
	},
	{
		name: "v_cw_cashflow_structure",
		from: "raw_caiwu",
		desc: "3. 现金流结构与质量 聚焦于“现金流 vs 利润 vs 收入”",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f218", alias: "operating_cf_per_share", desc: "每股经营性现金流(元)"},
			{name: "f219", alias: "cash_content_of_revenue", desc: "营业收入现金含量(%)"},
			{name: "f220", alias: "ocf_to_operating_profit_ratio", desc: "经营现金净额/经营净收益(%)"},
			{name: "f221", alias: "cash_received_to_revenue_ratio", desc: "销售现金/营业收入(%)"},
			{name: "f222", alias: "ocf_to_revenue_ratio", desc: "经营现金净额/营业收入"},
			{name: "f223", alias: "capex_to_depreciation_ratio", desc: "资本支出/折旧和摊销"},
			{name: "f224", alias: "net_cash_flow_per_share", desc: "每股现金流量净额(元)"},
			{name: "f225", alias: "operating_cf_to_short_term_debt_ratio", desc: "经营净现金比率（短期债务）"},
			{name: "f226", alias: "operating_cf_to_total_debt_ratio", desc: "经营净现金比率（全部债务）"},
			{name: "f227", alias: "ocf_to_net_profit_ratio", desc: "经营现金净流量/净利润"},
			{name: "f228", alias: "cash_return_on_total_assets", desc: "全部资产现金回收率"},
			{name: "f560", alias: "other_cash_effects2", desc: "其他原因对现金的影响2"},
			{name: "f576", alias: "cash_received_from_minority_investments_in_subsidiaries", desc: "子公司吸收少数股东投资收到的现金"},
			{name: "f577", alias: "dividends_paid_to_minority_shareholders", desc: "子公司支付给少数股东的股利、利润"},
			{name: "f578", alias: "depreciation_amortisation_of_investment_properties", desc: "投资性房地产折旧及摊销"},
			{name: "f579", alias: "credit_impairment_losses_cf", desc: "信用减值损失（现金流相关）"},
			{name: "f580", alias: "depreciation_of_right_of_use_assets", desc: "使用权资产折旧"},
		},
	},
	{
		name: "v_cw_holding_structure",
		from: "raw_caiwu",
		desc: "4. 股本结构 & 股东/机构持股",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f237", alias: "total_shares", desc: "总股本"},
			{name: "f238", alias: "float_a_shares", desc: "已上市流通A股"},
			{name: "f239", alias: "float_b_shares", desc: "已上市流通B股"},
			{name: "f240", alias: "float_h_shares", desc: "已上市流通H股"},
			{name: "f241", alias: "number_of_shareholders", desc: "股东人数(户)"},
			{name: "f242", alias: "shares_held_by_largest_shareholder", desc: "第一大股东持股数量"},
			{name: "f243", alias: "shares_held_by_top10_float_shareholders", desc: "十大流通股东持股合计"},
			{name: "f244", alias: "shares_held_by_top10_shareholders", desc: "十大股东持股合计"},
			{name: "f263", alias: "a_shares_held_by_top10_float_shareholders", desc: "十大流通股东中A股合计"},
			{name: "f264", alias: "shares_held_by_largest_float_shareholder", desc: "第一大流通股东持股量"},
			{name: "f265", alias: "free_float_shares", desc: "自由流通股"},
			{name: "f266", alias: "restricted_float_a_shares", desc: "受限流通A股"},
			{name: "f319", alias: "number_of_employees", desc: "员工总数(人)"},
			{name: "f245", alias: "total_institutions", desc: "机构总量(家)"},
			{name: "f246", alias: "total_institutional_shares", desc: "机构持股总量(股)"},
			{name: "f247", alias: "qfii_institutions", desc: "QFII机构数"},
			{name: "f248", alias: "qfii_shares", desc: "QFII持股量"},
			{name: "f249", alias: "securities_firm_institutions", desc: "券商机构数"},
			{name: "f250", alias: "securities_firm_shares", desc: "券商持股量"},
			{name: "f251", alias: "insurance_institutions", desc: "保险机构数"},
			{name: "f252", alias: "insurance_shares", desc: "保险持股量"},
			{name: "f253", alias: "fund_institutions", desc: "基金机构数"},
			{name: "f254", alias: "fund_shares", desc: "基金持股量"},
			{name: "f255", alias: "social_security_institutions", desc: "社保机构数"},
			{name: "f256", alias: "social_security_shares", desc: "社保持股量"},
			{name: "f257", alias: "private_equity_institutions", desc: "私募机构数"},
			{name: "f258", alias: "private_equity_shares", desc: "私募持股量"},
			{name: "f259", alias: "finance_company_institutions", desc: "财务公司机构数"},
			{name: "f260", alias: "finance_company_shares", desc: "财务公司持股量"},
			{name: "f261", alias: "pension_institutions", desc: "年金机构数"},
			{name: "f262", alias: "pension_shares", desc: "年金持股量"},
			{name: "f271", alias: "bank_institutions", desc: "银行机构数"},
			{name: "f272", alias: "bank_shares", desc: "银行持股量"},
			{name: "f273", alias: "general_corporate_institutions", desc: "一般法人机构数"},
			{name: "f274", alias: "general_corporate_shares", desc: "一般法人持股量"},
			{name: "f276", alias: "trust_institutions", desc: "信托机构数"},
			{name: "f277", alias: "trust_shares", desc: "信托持股量"},
			{name: "f278", alias: "special_corporate_institutions", desc: "特殊法人机构数"},
			{name: "f279", alias: "special_corporate_shares", desc: "特殊法人持股量"},
			{name: "f283", alias: "state_team_shares", desc: "国家队持股数量（万股）"},
			{name: "f324", alias: "northbound_institutions", desc: "北上资金机构数"},
			{name: "f325", alias: "northbound_shares", desc: "北上资金持股量"},
		},
	},
	{
		name: "v_cw_event_forecast",
		from: "raw_caiwu",
		desc: "5. 预告 / 快报 / 公告事件",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f284", alias: "guidance_net_profit_yoy_low", desc: "本期净利润同比增幅下限(%)"},
			{name: "f285", alias: "guidance_net_profit_yoy_high", desc: "本期净利润同比增幅上限(%)"},
			{name: "f286", alias: "flash_net_profit_attributable_to_owners", desc: "归母净利润（业绩快报）"},
			{name: "f287", alias: "flash_net_profit_excl_extra", desc: "扣非净利润（业绩快报）"},
			{name: "f288", alias: "flash_total_assets", desc: "总资产（业绩快报）"},
			{name: "f289", alias: "flash_net_assets", desc: "净资产（业绩快报）"},
			{name: "f290", alias: "flash_eps", desc: "每股收益（业绩快报）"},
			{name: "f291", alias: "flash_roe_diluted", desc: "摊薄净资产收益率（业绩快报）"},
			{name: "f292", alias: "flash_roe_weighted", desc: "加权净资产收益率（业绩快报）"},
			{name: "f293", alias: "flash_net_assets_ps", desc: "每股净资产（业绩快报）"},
			{name: "f312", alias: "guidance_announcement_date", desc: "业绩预告公告日期"},
			{name: "f313", alias: "report_announcement_date", desc: "财报公告日期"},
			{name: "f314", alias: "flash_report_announcement_date", desc: "业绩快报公告日期"},
			{name: "f316", alias: "guidance_net_profit_low", desc: "本期净利润下限(万元)"},
			{name: "f317", alias: "guidance_net_profit_high", desc: "本期净利润上限(万元)"},
			{name: "f329", alias: "flash_revenue_current", desc: "快报-营业收入（本期）"},
			{name: "f330", alias: "flash_revenue_prior", desc: "快报-营业收入（上期）"},
			{name: "f331", alias: "flash_operating_profit_current", desc: "快报-营业利润（本期）"},
			{name: "f332", alias: "flash_operating_profit_prior", desc: "快报-营业利润（上期）"},
			{name: "f333", alias: "flash_total_profit_current", desc: "快报-利润总额（本期）"},
			{name: "f334", alias: "flash_total_profit_prior", desc: "快报-利润总额（上期）"},
			{name: "f335", alias: "audit_opinion_code", desc: "审计意见"},
		},
	},
	{
		name: "v_cw_industry_ext",
		from: "raw_caiwu",
		desc: "6. 金融/保险/券商行业专属扩展",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f401", alias: "settlement_reserve", desc: "结算备付金"},
			{name: "f402", alias: "funds_lent", desc: "拆出资金"},
			{name: "f403", alias: "loans_and_advances_current", desc: "发放贷款及垫款(流动资产)"},
			{name: "f404", alias: "derivative_financial_assets", desc: "衍生金融资产"},
			{name: "f405", alias: "premiums_receivable", desc: "应收保费"},
			{name: "f406", alias: "reinsurance_receivables", desc: "应收分保账款"},
			{name: "f407", alias: "receivables_from_reinsurers_on_reserves", desc: "应收分保合同准备金"},
			{name: "f408", alias: "financial_assets_purchased_under_resale_agreements", desc: "买入返售金融资产"},
			{name: "f409", alias: "assets_held_for_sale", desc: "划分为持有待售的资产"},
			{name: "f410", alias: "loans_and_advances_noncurrent", desc: "发放贷款及垫款(非流动资产)"},
			{name: "f411", alias: "borrowings_from_central_bank", desc: "向中央银行借款"},
			{name: "f412", alias: "deposits_from_customers_and_banks", desc: "吸收存款及同业存放"},
			{name: "f413", alias: "funds_borrowed", desc: "拆入资金"},
			{name: "f414", alias: "derivative_financial_liabilities", desc: "衍生金融负债"},
			{name: "f415", alias: "financial_assets_sold_under_repurchases", desc: "卖出回购金融资产款"},
			{name: "f416", alias: "fees_and_commissions_payable", desc: "应付手续费及佣金"},
			{name: "f417", alias: "reinsurance_payables", desc: "应付分保账款"},
			{name: "f418", alias: "insurance_contract_reserves", desc: "保险合同准备金"},
			{name: "f419", alias: "agency_trading_securities_funds", desc: "代理买卖证券款"},
			{name: "f420", alias: "agency_underwriting_securities_funds", desc: "代理承销证券款"},
			{name: "f421", alias: "liabilities_held_for_sale", desc: "划分为持有待售的负债"},
			{name: "f422", alias: "provisions_ext", desc: "预计负债"},
			{name: "f423", alias: "deferred_income_current", desc: "递延收益（流动负债）"},
			{name: "f424", alias: "preference_shares_liability", desc: "优先股（负债）"},
			{name: "f425", alias: "perpetual_bonds_liability", desc: "永续债（负债）"},
			{name: "f426", alias: "long_term_employee_benefits_payable", desc: "长期应付职工薪酬"},
			{name: "f427", alias: "preference_shares_equity", desc: "优先股（权益）"},
			{name: "f428", alias: "perpetual_bonds_equity", desc: "永续债（权益）"},
			{name: "f429", alias: "debt_investments", desc: "债权投资"},
			{name: "f430", alias: "other_debt_investments", desc: "其他债权投资"},
			{name: "f431", alias: "other_equity_investments", desc: "其他权益工具投资"},
			{name: "f432", alias: "other_noncurrent_financial_assets", desc: "其他非流动金融资产"},
			{name: "f433", alias: "contract_liabilities", desc: "合同负债"},
			{name: "f434", alias: "contract_assets", desc: "合同资产"},
			{name: "f435", alias: "other_assets_ext", desc: "其他资产"},
			{name: "f436", alias: "receivables_financing", desc: "应收款项融资"},
			{name: "f437", alias: "right_of_use_assets", desc: "使用权资产"},
			{name: "f438", alias: "lease_liabilities", desc: "租赁负债"},
			{name: "f439", alias: "loans_and_advances", desc: "发放贷款及垫款"},
			{name: "f440", alias: "accounts_receivable_ext", desc: "应收款项"},
			{name: "f441", alias: "guarantee_deposits_paid", desc: "存出保证金"},
			{name: "f505", alias: "interest_income", desc: "利息收入"},
			{name: "f506", alias: "earned_premiums", desc: "已赚保费"},
			{name: "f507", alias: "fee_and_commission_income", desc: "手续费及佣金收入"},
			{name: "f508", alias: "interest_expense", desc: "利息支出"},
			{name: "f509", alias: "fee_and_commission_expense", desc: "手续费及佣金支出"},
			{name: "f510", alias: "surrender_payments", desc: "退保金"},
			{name: "f511", alias: "net_claims_paid", desc: "赔付支出净额"},
			{name: "f512", alias: "net_change_in_insurance_contract_reserves", desc: "提取保险合同准备金净额"},
			{name: "f513", alias: "policy_dividends_expense", desc: "保单红利支出"},
			{name: "f514", alias: "reinsurance_expense", desc: "分保费用"},
			{name: "f561", alias: "net_increase_in_customer_and_bank_deposits", desc: "客户存款和同业存放款项净增加额"},
			{name: "f562", alias: "net_increase_in_borrowings_from_central_bank", desc: "向中央银行借款净增加额"},
			{name: "f563", alias: "net_increase_in_borrowings_from_fis", desc: "向其他金融机构拆入资金净增加额"},
			{name: "f564", alias: "cash_received_from_original_insurance_premiums", desc: "收到原保险合同保费取得的现金"},
			{name: "f565", alias: "net_cash_received_from_reinsurance", desc: "收到再保险业务现金净额"},
			{name: "f566", alias: "net_increase_in_policyholder_deposits_and_investments", desc: "保户储金及投资款净增加额"},
			{name: "f567", alias: "net_increase_from_fv_pl_financial_assets_disposal", desc: "处置以公允价值计量且变动计入当期损益金融资产净增加额"},
			{name: "f568", alias: "cash_received_from_interest_fees_commissions", desc: "收取利息、手续费及佣金的现金"},
			{name: "f569", alias: "net_increase_in_funds_borrowed", desc: "拆入资金净增加额"},
			{name: "f570", alias: "net_increase_in_repo_business_funds", desc: "回购业务资金净增加额"},
			{name: "f571", alias: "net_increase_in_loans_and_advances", desc: "客户贷款及垫款净增加额"},
			{name: "f572", alias: "net_increase_in_deposits_with_cb_and_banks", desc: "存放中央银行和同业款项净增加额"},
			{name: "f573", alias: "cash_paid_for_original_insurance_claims", desc: "支付原保险合同赔付款项的现金"},
			{name: "f574", alias: "cash_paid_for_interest_fees_commissions", desc: "支付利息、手续费及佣金的现金"},
			{name: "f575", alias: "cash_paid_for_policy_dividends", desc: "支付保单红利的现金"},
		},
	},
	{
		name: "v_cw_factor_input",
		from: "raw_caiwu",
		desc: "7. 财务因子库",
		fields: []ColumnView{
			{name: "code", desc: "证券代码"},
			{name: "report_date", alias: "rdate", desc: "报告期"},
			{name: "f0", alias: "eps_basic", desc: "基本每股收益"},
			{name: "f1", alias: "eps_excl_extra", desc: "扣非每股收益"},
			{name: "f3", alias: "nav_ps", desc: "每股净资产"},
			{name: "f5", alias: "roe_basic", desc: "净资产收益率（每股指标口径）"},
			{name: "f73", alias: "operating_revenue", desc: "营业收入"},
			{name: "f85", alias: "operating_profit", desc: "营业利润"},
			{name: "f91", alias: "total_profit", desc: "利润总额"},
			{name: "f95", alias: "net_profit_parent", desc: "归母净利润"},
			{name: "f205", alias: "net_profit_excl_extra", desc: "扣非归母净利润"},
			{name: "f20", alias: "total_current_assets", desc: "流动资产合计"},
			{name: "f26", alias: "fixed_assets", desc: "固定资产"},
			{name: "f39", alias: "total_assets", desc: "资产总计"},
			{name: "f53", alias: "total_current_liabilities", desc: "流动负债合计"},
			{name: "f62", alias: "total_liabilities", desc: "负债合计"},
			{name: "f71", alias: "total_equity", desc: "所有者权益合计"},
			{name: "f270", alias: "equity_attributable_to_owners", desc: "归母股东权益（资产负债表）"},
			{name: "f193", alias: "operating_margin_pct", desc: "营业利润率(%)"},
			{name: "f196", alias: "roe", desc: "净资产收益率(通常口径)"},
			{name: "f197", alias: "investment_return_pct", desc: "投资收益率(%)"},
			{name: "f198", alias: "sales_net_margin_pct", desc: "销售净利率(%)"},
			{name: "f199", alias: "roa", desc: "总资产净利率"},
			{name: "f200", alias: "net_profit_margin_pct", desc: "净利润率(%)"},
			{name: "f201", alias: "gross_margin_pct", desc: "销售毛利率(%)"},
			{name: "f208", alias: "ebitda_margin_pct", desc: "EBITDA 利润率(%)"},
			{name: "f280", alias: "roe_weighted", desc: "加权 ROE"},
			{name: "f328", alias: "roic", desc: "ROIC 投入资本回报率"},
			{name: "f182", alias: "revenue_growth_yoy_pct", desc: "营业收入同比增速(%)"},
			{name: "f183", alias: "net_profit_growth_yoy_pct", desc: "净利润同比增速(%)"},
			{name: "f186", alias: "total_assets_growth_yoy_pct", desc: "总资产同比增速(%)"},
			{name: "f188", alias: "operating_profit_growth_yoy_pct", desc: "营业利润同比增速(%)"},
			{name: "f189", alias: "eps_excl_extra_growth_yoy_pct", desc: "扣非 EPS 同比(%)"},
			{name: "f190", alias: "net_profit_excl_extra_growth_yoy_pct", desc: "扣非净利润同比(%)"},
			{name: "f158", alias: "current_ratio", desc: "流动比率"},
			{name: "f159", alias: "quick_ratio", desc: "速动比率"},
			{name: "f160", alias: "cash_ratio_pct", desc: "现金比率(%)"},
			{name: "f161", alias: "interest_coverage", desc: "利息保障倍数"},
			{name: "f209", alias: "debt_to_asset_pct", desc: "资产负债率(%)"},
			{name: "f166", alias: "equity_multiplier_pct", desc: "权益乘数(%)"},
			{name: "f169", alias: "ocf_to_total_liabilities_pct", desc: "经营现金流 / 负债合计(%)"},
			{name: "f170", alias: "ebitda_to_total_liabilities_pct", desc: "EBITDA / 负债合计(%)"},
			{name: "f165", alias: "tangible_net_worth_to_debt_pct", desc: "有形净资产 / 债务(%)"},
			{name: "f326", alias: "interest_bearing_debt_ratio", desc: "有息负债率"},
			{name: "f171", alias: "ar_turnover", desc: "应收账款周转率"},
			{name: "f172", alias: "inventory_turnover", desc: "存货周转率"},
			{name: "f174", alias: "asset_turnover", desc: "总资产周转率"},
			{name: "f176", alias: "ar_turnover_days", desc: "应收账款周转天数"},
			{name: "f177", alias: "inventory_turnover_days", desc: "存货周转天数"},
			{name: "f181", alias: "equity_turnover", desc: "股东权益周转率"},
			{name: "f218", alias: "ocf_per_share", desc: "每股经营性现金流"},
			{name: "f219", alias: "cash_content_of_revenue_pct", desc: "收入现金含量(%)"},
			{name: "f220", alias: "ocf_to_operating_profit_pct", desc: "经营现金流 / 经营收益(%)"},
			{name: "f221", alias: "cash_sales_to_revenue_pct", desc: "现金售货 / 营业收入(%)"},
			{name: "f222", alias: "ocf_to_revenue", desc: "经营现金流 / 营业收入"},
			{name: "f223", alias: "capex_to_depr", desc: "资本支出 / 折旧摊销"},
			{name: "f224", alias: "net_cf_per_share", desc: "每股现金流量净额"},
			{name: "f225", alias: "ocf_to_short_term_debt", desc: "经营净现金比率(短期债务)"},
			{name: "f226", alias: "ocf_to_total_debt", desc: "经营净现金比率(全部债务)"},
			{name: "f227", alias: "ocf_to_net_profit", desc: "经营现金流 / 净利润"},
			{name: "f228", alias: "cash_return_on_assets", desc: "资产现金回收率"},
			{name: "f106", alias: "net_cash_from_operating_activities", desc: "经营活动现金流净额"},
			{name: "f118", alias: "net_cash_from_investing_activities", desc: "投资活动现金流净额"},
			{name: "f127", alias: "net_cash_from_financing_activities", desc: "筹资活动现金流净额"},
			{name: "f130", alias: "net_increase_in_cash_and_equivalents", desc: "现金及等价物净增加额"},
			{name: "f306", alias: "ocf_last_12m", desc: "近一年经营活动现金流净额"},
			{name: "f309", alias: "net_cash_flow_last_12m", desc: "近一年现金净流量"},
			{name: "f315", alias: "investing_cf_last_12m", desc: "近一年投资活动现金流净额"},
			{name: "f320", alias: "free_cf_to_firm_ps", desc: "每股企业自由现金流"},
			{name: "f321", alias: "free_cf_to_equity_ps", desc: "每股股东自由现金流"},
			{name: "f237", alias: "total_shares", desc: "总股本"},
			{name: "f238", alias: "float_a_shares", desc: "已上市流通 A 股"},
			{name: "f265", alias: "free_float_shares", desc: "自由流通股"},
			{name: "f241", alias: "shareholder_count", desc: "股东户数"},
			{name: "f242", alias: "largest_shareholder_shares", desc: "第一大股东持股"},
			{name: "f243", alias: "top10_float_shareholders_shares", desc: "十大流通股东持股合计"},
			{name: "f245", alias: "institution_count", desc: "机构数"},
			{name: "f246", alias: "institutional_shares", desc: "机构持股量"},
			{name: "f324", alias: "northbound_institution_count", desc: "北上资金机构数"},
			{name: "f325", alias: "northbound_shares", desc: "北上资金持股量"},
			{name: "f335", alias: "audit_opinion_code", desc: "审计意见(0-未审计,1-无保留,…)"},
			{name: "f336", alias: "dividend_payout_ratio_pct", desc: "股利支付率(%)"},
		},
	},
}

func CreateCwViews(db *sql.DB) error {
	for _, view := range cwViews {
		if err := createView(db, view); err != nil {
			return err
		}
	}
	return nil
}
